-- Flux métier : une commande n'affecte jamais le stock ; seule une réception validée pourra générer un mouvement.
create table public.purchase_orders (id uuid primary key default gen_random_uuid(), establishment_id uuid not null references public.establishments(id) on delete cascade, supplier_id uuid references public.suppliers(id) on delete set null, status text not null default 'draft' check(status in ('draft','sent','partially_received','received','cancelled')), notes text, ordered_by uuid not null references public.profiles(id), ordered_at timestamptz not null default now(), expected_at date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.purchase_order_lines (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.purchase_orders(id) on delete cascade, product_id uuid not null references public.products(id) on delete restrict, quantity numeric not null check(quantity>0), unit text not null default 'unité', unit_price numeric check(unit_price>=0), pack_quantity numeric not null default 1 check(pack_quantity>0));
create table public.receipts (id uuid primary key default gen_random_uuid(), establishment_id uuid not null references public.establishments(id) on delete cascade, order_id uuid references public.purchase_orders(id) on delete set null, status text not null default 'draft' check(status in ('draft','checked','validated','cancelled')), received_by uuid not null references public.profiles(id), received_at timestamptz not null default now(), validated_by uuid references public.profiles(id), validated_at timestamptz, note text, check((status='validated')=(validated_by is not null and validated_at is not null)));
create table public.receipt_lines (id uuid primary key default gen_random_uuid(), receipt_id uuid not null references public.receipts(id) on delete cascade, product_id uuid not null references public.products(id) on delete restrict, expected_quantity numeric, received_quantity numeric not null check(received_quantity>=0), unit text not null default 'unité', unit_price numeric check(unit_price>=0), missing_quantity numeric not null default 0 check(missing_quantity>=0), note text);
alter table public.purchase_orders enable row level security; alter table public.purchase_order_lines enable row level security; alter table public.receipts enable row level security; alter table public.receipt_lines enable row level security;
revoke all on public.purchase_orders,public.purchase_order_lines,public.receipts,public.receipt_lines from anon,authenticated; grant select,insert,update on public.purchase_orders,public.purchase_order_lines,public.receipts,public.receipt_lines to authenticated;
create policy "Members read orders" on public.purchase_orders for select to authenticated using ((select private.is_establishment_member(establishment_id)));
create policy "Management writes orders" on public.purchase_orders for insert to authenticated with check (ordered_by=(select auth.uid()) and (select private.has_establishment_role(establishment_id,array['administrateur','gestion']::public.app_role[])));
create policy "Management updates orders" on public.purchase_orders for update to authenticated using ((select private.has_establishment_role(establishment_id,array['administrateur','gestion']::public.app_role[]))) with check ((select private.has_establishment_role(establishment_id,array['administrateur','gestion']::public.app_role[])));
create policy "Members read receipts" on public.receipts for select to authenticated using ((select private.is_establishment_member(establishment_id)));
create policy "Management creates receipts" on public.receipts for insert to authenticated with check (received_by=(select auth.uid()) and (select private.has_establishment_role(establishment_id,array['administrateur','gestion']::public.app_role[])));
create policy "Management validates receipts" on public.receipts for update to authenticated using ((select private.has_establishment_role(establishment_id,array['administrateur','gestion']::public.app_role[]))) with check ((status<>'validated' or validated_by=(select auth.uid())) and (select private.has_establishment_role(establishment_id,array['administrateur','gestion']::public.app_role[])));
