/* SWAY · core */

/* Logique de SWAY : extraite de l'ancienne page unique. */

const Store=(()=>{const mem={};const hasW=typeof window.storage!=='undefined'&&window.storage;
let hasLS=false;try{localStorage.setItem('__t','1');localStorage.removeItem('__t');hasLS=true}catch(e){}
return{async get(k){if(hasW){try{const r=await window.storage.get(k);return r?JSON.parse(r.value):null}catch(e){return null}}
if(hasLS){const v=localStorage.getItem(k);return v?JSON.parse(v):null}return mem[k]??null},
async set(k,v){if(hasW){try{await window.storage.set(k,JSON.stringify(v));return}catch(e){}}
if(hasLS){try{localStorage.setItem(k,JSON.stringify(v));return}catch(e){}}mem[k]=v}}})();

const L={
fr:{code:'FR',nom:'Français',fl:'🇫🇷',
pvModifier:'Modifier les prix',pvTous:'Tous',pvAide:'Modifiez directement les prix de vente. Le ratio matière se recalcule à chaque frappe. Rien n\'est enregistré tant que vous ne validez pas.',pvCout:'Coût',pvAvant:'avant :',pvAppliquer:'Appliquer à tous les produits affichés (%n)',pvAucun:'Aucun produit ne correspond.',pvEnregistrer:'Enregistrer %n prix',pvRien:'Aucune modification',pvEnregistres:'%n prix mis à jour',

qCoupe:'Le bon touche deux bords de l\'image : une partie peut manquer.',qCoupeFort:'Document incomplet : reculez ou recentrez pour voir le bon en entier.',qReflet:'Un reflet éclaircit une partie du document.',qRefletFort:'Reflet important : une partie du texte est effacée. Changez l\'angle ou éloignez la source de lumière.',qVerdictVert:'Photo exploitable, la lecture peut être lancée.',qVerdictOrange:'Photo imparfaite mais exploitable : le prétraitement devrait suffire.',qVerdictRouge:'Photo probablement inexploitable pour la lecture automatique.',

trProduitInconnu:'« %p » n\'existe pas au catalogue : enregistrez-le d\'abord dans Produits.',trQteInvalide:'Quantité invalide.',trMotifInconnu:'Motif de mouvement inconnu.',trAnnulSansVente:'Impossible de valider : enregistre d’abord la vente ou la transaction d’origine pour ce produit.',trParentAbsent:'La transaction d\'origine est introuvable.',trParentInvalide:'Cette qualification ne peut porter que sur une vente ou un envoi.',trParentAutreProduit:'La transaction d\'origine concerne un autre produit.',trDejaAnnule:'Cette transaction est déjà entièrement qualifiée.',trAnnulTrop:'Qualification de %q demandée, mais il ne reste que %r à qualifier.',trStockInsuffisant:'Stock insuffisant : %l',trAppuyerEncore:'Appuyez à nouveau pour enregistrer malgré tout.',trLiee:'liée à une transaction',trStockAlerte:'stock insuffisant au moment du mouvement',annul:'Annulation',annulD:'Annule une vente existante',

qViseur:'Placez le bon de livraison dans le cadre',qC1:'Posez le bon à plat, sur une surface unie',qC2:'Tenez le téléphone bien au-dessus, pas de biais',qC3:'Évitez les ombres portées et les reflets',qTitre:'Qualité de la photo',qBonne:'Bonne qualité, la lecture devrait bien se passer.',qFlou:'Photo floue : le texte risque d\'être illisible. Refaites-la en stabilisant le téléphone.',qPeuNet:'Photo un peu molle : la lecture sera moins fiable.',qSombre:'Photo trop sombre : allumez la lumière ou approchez-vous d\'une fenêtre.',qSurexpose:'Photo surexposée : le texte clair risque de disparaître.',qPeuContraste:'Peu de contraste entre le texte et le papier.',qTropLoin:'Le bon occupe une trop petite partie de l\'image : rapprochez-vous.',qUnPeuLoin:'Rapprochez-vous un peu, le texte sera plus net.',qIncline:'Document incliné de %a° : redressez-le pour aligner les colonnes.',qPetite:'Image de faible définition : le texte fin sera difficile à lire.',qConseilRefaire:'Nous vous conseillons de reprendre cette photo avant de lancer la lecture.',

scAConfirmer:'À confirmer',scConfirmerAide:'Invo propose « %p » (correspondance %s %). Confirmez si c\'est bien ce produit.',scConfirmer:'Oui, c\'est ce produit',scTexteLu:'Texte lu :',scDoublonPage:'Ligne identique déjà présente sur une autre page — vérifiez qu\'il ne s\'agit pas d\'un doublon.',scConfirmerDabord:'%n ligne(s) attendent votre confirmation avant validation.',

ctrlTitre:'Contrôles de cohérence',ctrlOk:'Tous les contrôles sont bons : quantités, prix et totaux concordent.',ctrlMulti:'%n : quantité × prix donne %c € mais le bon indique %t €',ctrlQteVide:'%n : quantité absente ou illisible',ctrlQteEnorme:'%n : quantité de %q, inhabituellement élevée',ctrlQtePetite:'%n : quantité de %q, à confirmer',ctrlPxVide:'%n : prix unitaire absent',ctrlPxEnorme:'%n : prix de %p €, inhabituellement élevé',ctrlPxInhab:'%n : %p € alors que vous payez habituellement %h €',ctrlQteInhab:'%n : %q reçus alors que vous recevez habituellement %h',ctrlDoublonLigne:'%n apparaît deux fois à l\'identique dans ce bon',ctrlSomme:'La somme des lignes fait %s € mais le bon indique %h € HT (écart de %d €)',ctrlHtTva:'HT %h € + TVA %v € ne donne pas le TTC %t €',ctrlTaux:'Taux de TVA calculé à %x %, inhabituel',ctrlAucuneLigne:'Aucune ligne exploitable : renseignez au moins un produit avec sa quantité',ctrlBloque:'%n anomalie(s) grave(s) détectée(s). Corrigez-les, ou appuyez à nouveau pour valider malgré tout.',ctrlValiderQuandMeme:'Valider malgré les anomalies',

scCond:'Conditionnement',scDe:'de',scEnUnites:'unités',scConverti:'Converti en unités',scMethColonnes:'tableau analysé par colonnes',scMethMixte:'analyse mixte',scMethLignes:'analyse ligne par ligne',scImageOpt:'Image optimisée :',scRecadre:'recadrée',scRedresse:'redressée de %a°',

scOcrBloque:'Ce navigateur bloque le moteur de lecture. Ouvrez Invo dans Safari ou Chrome (plutôt que depuis un aperçu) pour utiliser la lecture automatique. En attendant, saisissez les lignes à la main.',scRelire:'Réessayer la lecture',

scAnalyse:'Lecture du document…',scPage:'Page',scPatience:'Le moteur de lecture se télécharge au premier usage. Les fois suivantes seront plus rapides.',scLu:'%n ligne(s) lue(s). Vérifiez avant de valider.',scPartiel:'%n ligne(s) lue(s), dont %i à vérifier (signalées en orange).',scRienLu:'Aucune ligne de produit n\'a pu être lue. Saisissez-les à la main en vous aidant de la photo.',scOcrHorsLigne:'Lecture automatique indisponible (connexion requise au premier usage). Saisissez les lignes à la main.',scOcrEchec:'La lecture du document a échoué. Saisissez les lignes à la main.',scMoteur:'Lu automatiquement',scFiab:'fiabilité',scFiabBasse:'Fiabilité faible : relisez chaque ligne attentivement.',scVerifChamp:'À vérifier',scLeProduit:'le produit',scUnite:'Unité :',

scScannerBon:'Scanner un bon',scTitre:'Scanner un bon de livraison',scCaptureS:'Photographiez le bon. Vous pourrez tout vérifier avant validation.',scPhoto:'Prendre une photo',scGalerie:'Choisir une image',scPages:'Pages',scAmeliorer:'Améliorer la lisibilité',scAmeliorerS:'Contraste renforcé pour les bons pâles',scAnalyser:'Analyser le bon',scAnalyse:'Analyse en cours…',scTraitement:'Traitement de l\'image…',scAucunePage:'Ajoutez au moins une photo du bon.',scVerifTitre:'Vérifier la livraison',scVerifS:'Contrôlez chaque ligne. Le stock ne sera modifié qu\'après validation.',scOcrIndispo:'La lecture automatique n\'est pas encore connectée. Le document est conservé — saisissez les lignes en vous aidant de la photo ci-dessus.',scVerifiez:'Informations détectées. Vérifiez-les avant de valider.',scFournisseur:'Fournisseur',scNumBl:'N° de bon',scDate:'Date',scProduits:'Produits',scLigne:'Ligne',scLignes:'lignes',scReconnu:'Reconnu',scNonReconnu:'À vérifier',scInconnuAide:'Ce produit n\'a pas été reconnu. Que faire ?',scAssocier:'Associer à un produit',scCreer:'Créer le produit',scIgnorer:'Ignorer',scQte:'Qté',scPu:'P.U. €',scRef:'Réf. fournisseur :',scAjouterLigne:'+ Ajouter une ligne',scAucuneLigne:'Aucune ligne pour l\'instant.',scLignesSaisies:'Lignes',scTotal:'Total',scBrouillon:'Brouillon',scValider:'Valider la livraison',scBrouillonOk:'Brouillon enregistré',scBrouillons:'Brouillons',scSansFournisseur:'Sans fournisseur',scValide:'Livraison validée, stock mis à jour',scRienAValider:'Renseignez au moins un produit avec une quantité.',scFoManquant:'Indiquez le fournisseur avant de valider.',scErrEnreg:'Une erreur est survenue. Vos données n\'ont pas été modifiées.',scDoublon:'Cette livraison semble déjà enregistrée.',scVoirExistante:'Voir la livraison existante',scContinuer:'Continuer quand même',scDocument:'Document',scDocPurge:'Le document n\'est plus conservé (limite d\'espace atteinte).',scScanne:'Scanné',scManuel:'Manuel',scProduitCree:'Produit créé',scNouveauProduit:'Nouveau produit',scProduitSupprime:'Produit supprimé',errType:'Ce fichier n\'est pas une image.',errTaille:'Image trop volumineuse (25 Mo maximum).',errLecture:'Impossible de lire le fichier.',errImage:'Impossible de lire le document.',errTraitement:'Le traitement de l\'image a échoué.',

ruptLoin:'Stock suffisant',perteDans:'À écouler sous %s j',perteDetail:'Environ %q %u seront perdus (%v €) — conservation %d j seulement.',prevPerte:'Risque de perte',prevPerteS:'Vous en avez plus que ce que vous consommerez avant la date limite.',anoPerte:'%s produit(s) frais en surstock — %v € menacés',conservation:'conservation',fDlc:'Durée de conservation (jours)',fDlcAide:'Combien de jours le produit se garde après réception. Laissez 0 pour les alcools et les produits secs.',

tabPrev:'Prévisions',prevVideT:'Pas encore assez de données',prevVideD:'Les prévisions apparaîtront dès que des ventes auront été enregistrées.',prevBase:'Calculé sur %s journée(s) d\'activité réellement observée(s).',prevPeuFiable:'Estimation basée sur une seule journée. La précision augmentera avec les jours.',prevUrgent:'À commander maintenant',prevSuivre:'À surveiller cette semaine',prevOk:'Stock confortable',ruptMaintenant:'Rupture imminente',ruptAujourdhui:'Rupture aujourd\'hui',ruptDemain:'Rupture demain',ruptDans:'Rupture dans %s j',ruptDeja:'En rupture',resteEn:'Reste %s %u',rythme:'consommation %s %u/jour',anoRupturePrevue:'%s : rupture prévue %q',anoRupturePrevueD:'%s autre(s) produit(s) concerné(s)',anoRythme:'Au rythme actuel de %s %u par jour.',

slogan:'INVO — Gardez le contrôle.',aConnexion:'Connexion',aConnexionS:'Retrouvez les données de votre établissement.',aMail:'Adresse e-mail',aPwd:'Mot de passe',aPwd2:'Confirmer le mot de passe',aSeConnecter:'Se connecter',aOubli:'Mot de passe oublié ?',aOu:'ou',aCreerCompte:'Créer un compte',aCreerS:'Un compte par établissement. Vos données restent séparées de celles des autres.',aNom:'Votre nom',aEtab:'Nom de l\'établissement',aCreer:'Créer mon compte',aDejaCompte:'J\'ai déjà un compte',aCodeTitre:'Votre code de secours',aCodeS:'Notez-le maintenant. Il permet de réinitialiser votre mot de passe si vous l\'oubliez.',aCodeNote:'Ce code ne sera plus affiché. Rangez-le en lieu sûr.',aEntrer:'J\'ai noté, entrer dans Invo',aOubliTitre:'Réinitialiser le mot de passe',aOubliS:'Saisissez le code de secours reçu à la création du compte.',aCode:'Code de secours',aNouveauPwd:'Nouveau mot de passe',aReinit:'Réinitialiser',aRetourConnexion:'Retour à la connexion',aReinitOk:'Mot de passe modifié. Vous pouvez vous connecter.',aChamps:'Merci de remplir tous les champs.',aMailInvalide:'Adresse e-mail invalide.',aPwdCourt:'Le mot de passe doit faire au moins 8 caractères.',aPwdDiff:'Les deux mots de passe ne correspondent pas.',aDejaPris:'Un compte existe déjà avec cette adresse.',aIntrouvable:'Aucun compte avec cette adresse.',aMauvaisPwd:'Mot de passe incorrect.',aCodeFaux:'Code de secours incorrect.',reglages:'Réglages',reglagesS:'Établissement et matériel connecté.',sauvegarde:'Sauvegarde locale',sauvegardeS:'Conservez une copie avant de changer d’appareil. Les données restent sur cet appareil : aucun envoi en ligne.',exportSauvegarde:'⬇ Télécharger la sauvegarde',importSauvegarde:'↥ Restaurer une sauvegarde',importAide:'La restauration remplace les données de cet appareil. Une copie des données actuelles sera téléchargée juste avant.',backupPreparing:'Préparation de la sauvegarde…',backupOk:'Sauvegarde téléchargée',backupFormat:'Ce fichier n’est pas une sauvegarde INVO valide.',backupTooBig:'Sauvegarde trop volumineuse (120 Mo maximum).',backupRead:'Impossible de lire cette sauvegarde.',backupConfirm:'Restaurer cette sauvegarde va remplacer toutes les données locales de cet appareil. Une copie des données actuelles sera téléchargée avant la restauration. Continuer ?',backupRestored:'Sauvegarde restaurée',pilot:'Test pilote',pilotS:'Préparez une base vide pour tester INVO avec les vraies données de votre établissement.',pilotOn:'Test réel en cours : aucune donnée de démonstration n’est chargée.',pilotStart:'Démarrer le test réel',pilotConfirm:'Démarrer le test réel va retirer de cet appareil les produits, stocks et historiques de démonstration. Une sauvegarde sera téléchargée avant. Continuer ?',pilotReady:'Base pilote prête : ajoutez vos premiers produits réels.',pilotDemoS:'Préparez des données fictives : commande, livraison et ventes simulées depuis une caisse.',pilotDemoLoad:'Préparer la démo caisse',pilotDemoConfirm:'Préparer la démo caisse va remplacer les données locales actuelles. Une sauvegarde sera téléchargée avant. Continuer ?',pilotDemoReady:'Démo caisse prête. Vous pouvez contrôler la réception et les ventes simulées.',etablissement:'Établissement',nomEtab:'Nom',donneesIsolees:'Données séparées',donneesIsoleesS:'Les données de cet établissement ne sont pas visibles par les autres comptes.',compte:'Compte',seDeconnecter:'Se déconnecter',confDeco:'Se déconnecter d\'Invo ?',avertLocal:'Ouvert en fichier local : le chiffrement du mot de passe est limité. Pour un usage réel, hébergez l\'application en HTTPS.',materiel:'Matériel connecté',materielS:'Entièrement facultatif. Invo fonctionne normalement sans aucun matériel.',doseurs:'Doseurs électroniques',doseursS:'Bouteilles en stock',nonConfig:'Non configuré',activeManuel:'Saisie manuelle',sansDoseurs:'Je n\'en utilise pas',avecDoseurs:'J\'en utilise',futs:'Fûts connectés',futsS:'Bière pression',balances:'Balances connectées',balancesS:'Pesée en cuisine',aVenir:'À venir',fermer:'Fermer',doseursDemo:'Aucun doseur n\'est relié pour l\'instant. Saisissez un relevé à la main pour voir le calcul d\'écart. La connexion automatique nécessitera l\'API du fabricant.',theo:'Théorique',releve:'Relevé',ecart:'Écart',vsTheorique:'par rapport au théorique',theorique:'Théorique :',reel:'Réel :',attention:'Ce qui mérite votre attention',rasT:'Rien d\'anormal détecté',rasD:'Les ratios, les stocks et les écarts sont dans les clous.',anoRatio:'Ratio matière à %s % — au-dessus de la cible',anoRatioD:'Dont %s € de sorties non vendues.',anoRupture:'%s produit(s) en rupture',anoSeuil:'%s produit(s) sous le seuil',anoDerive:'%s produit(s) en écart répété à l\'inventaire',anoPrix:'%s prix d\'achat en hausse',anoMarge:'%s produit(s) sous la marge cible',anoOfferts:'%s € d\'offerts sur la période',anoOffertsD:'Soit %s % du chiffre d\'affaires.',

accesTout:'Accès complet',accesEquipe:'Déclarer, livraisons, inventaire',
nLiv:'Livraisons',
livT:'Entrées de stock',livS:'Enregistrez ce que vous recevez : le stock remonte, les prix se mettent à jour.',
tabRecep:'Réception',tabCmd:'À commander',
newLiv:'+ Nouvelle livraison',fourn:'Fournisseur',dateL:'Date',
addLine:'+ Ajouter une ligne',totalLiv:'Total de la livraison',validLiv:'Enregistrer la livraison',
histLiv:'Livraisons récentes',noLiv:'Aucune livraison enregistrée pour l\'instant.',
qteRecue:'Qté reçue',prixU2:'Prix unitaire',livSaved:'Livraison enregistrée',
prixMaj:'Prix mis à jour',hausse:'Hausse',baisse:'Baisse',
cmdT:'Suggestion de commande',cmdS:'Produits passés sous leur seuil d\'alerte.',
aCommander:'À commander',copierListe:'📋 Copier la liste',listeCopiee:'Liste copiée',
noCmd:'Aucun produit sous le seuil. Tout va bien.',
zone:'Zone',zBar:'Bar',zCave:'Cave',zCuisine:'Cuisine',zReserve:'Réserve',zToutes:'Toutes',
tabCount:'Compter',tabHist:'Historique',
histT:'Inventaires précédents',noHist:'Aucun inventaire validé pour l\'instant.',
derive:'Dérive récurrente',deriveS:'En écart sur plusieurs inventaires — à surveiller.',
exportCsv:'⬇ Exporter (CSV)',imprimer:'🖨 Imprimer / PDF',
addPhoto:'📷 Ajouter une photo',photoOk:'Photo ajoutée',retirerPhoto:'Retirer la photo',
alertes:'Alertes',alertPrix:'Hausses de prix d\'achat',alertMarge:'Plats sous marge',
noAlerte:'Aucune alerte. Vos marges tiennent.',
valeurStock:'Valeur du stock',ecartValeur:'Valeur des écarts',
inventaireDu:'Inventaire du',lignesEcart:'lignes en écart',
nCaisse:'Ventes externes',nDec:'Déclarer',svc:'Service',nStock:'Produits',nInv:'Inventaire',nBil:'Bilan',
caisseT:'Flux des ventes externes',caisseS:'Enregistrez uniquement les sorties provenant de ventes déjà réalisées hors d’INVO. INVO n’encaisse aucun paiement.',
connected:'CONNECTÉ',connSub:'Dernière synchro il y a %s',
manualCaisse:'Suivi de stock : aucune donnée de paiement ou de caisse n’est créée automatiquement.',newVente:'+ Ajouter une vente externe',
aVerifier:'À vérifier',aVerifierS:'Ces sorties existent déjà. Classez uniquement celles qui deviennent un offert, une annulation ou une perte.',
verifVide:'Aucune vente externe à vérifier.',qualifier:'Classer une vente externe',qualifierS:'La sortie est déjà enregistrée. Le classement ne déduira pas le stock une seconde fois.',
resteQ:'Quantité à classer',confQual:'Valider le classement',qualSaved:'Classement enregistré',
demoCaisse:'Démonstration : ce flux simule un import de ventes externes. INVO ne traite aucun paiement.',
vente:'Vente externe',venteD:'Sortie de stock liée à une vente réalisée hors d’INVO',offClient:'Offert client',offPart:'Offert partenaire',offGroupe:'Offert groupe',
annul:'Annulation',perso:'Repas personnel',casse:'Casse',rate:'Raté / refait',degus:'Dégustation',entame:'Bouteille entamée',
offClientD:'Geste commercial en salle',offPartD:'Confrère, fournisseur, resto voisin',
offGroupeD:'Groupe, événement, privatisation',persoD:'Équipe salle ou cuisine',
casseD:'Tombé, cassé, renversé',rateD:'Brûlé, loupé, à refaire',
degusD:'Test carte, patron, fournisseur',entameD:'Ouverte, jamais soldée',
auto:'AUTO',manuel:'MANUEL',pause:'Mettre en pause',reprendre:'Reprendre le flux',
decT:'Déclarer une sortie',decS:'Tout ce qui quitte le stock sans provenir d’une vente externe.',
demoDec:'Touchez un produit pour l\'ajouter. Ajustez les quantités, choisissez le motif, validez d\'un coup.',
midi:'Midi',soir:'Soir',svcHint:'Le service filtre la carte : les plats le midi, les tapas et cocktails le soir.',
etape1:'1 — Produits',etape2:'2 — Motif',panier:'Panier',vider:'Vider',
coutMat:'Coût matière total',send:'Valider la sortie',articles:'article',articlesP:'articles',choisirMotif:'Choisir le motif',
stockT:'Produits & matières',stockS:'Ajoutez, modifiez ou retirez ce que vous voulez suivre.',
tabMat:'Matières',tabCarte:'Carte',search:'Chercher…',
addMat:'Ajouter une matière',editMat:'Modifier la matière',
addCarte:'Ajouter à la carte',editCarte:'Modifier le produit',
fNom:'Nom',fIcone:'Icône',fUnite:'Unité de suivi',fAchat:'Mode d\'achat',
achCont:'Au contenant',achDirect:'Au détail',fContenance:'Contenance',fPrixCont:'Prix d\'achat',
fPrixU:'Prix unitaire',fStock:'Stock actuel',fSeuil:'Seuil d\'alerte',
fCat:'Catégorie',fService:'Service',fType:'Type',fPV:'Prix de vente',
tFood:'Nourriture',tDrink:'Boisson',svTous:'Midi et soir',
fiche:'Fiche technique',ficheS:'Ce que le produit consomme réellement en stock.',
addIng:'+ Ajouter un ingrédient',noIng:'Aucun ingrédient — le coût matière sera nul.',
coutRev:'Coût de revient',marge:'Marge',ratioP:'Ratio',
save2:'Enregistrer',del:'Supprimer',cancel:'Annuler',
confDel:'Supprimer définitivement ?',usedIn:'Utilisé dans %s recette(s) — il en sera retiré.',
matSaved:'Matière enregistrée',matDel:'Matière supprimée',
carteSaved:'Produit enregistré',carteDel:'Produit supprimé',
invT:'Inventaire du mois',invS:'Comptez, comparez, validez. Seuls les écarts demandent du travail.',
attendu:'ATTENDU',compte:'COMPTÉ',prod:'PRODUIT',valid:'Valider l\'inventaire',clear:'Tout effacer',
lignes:'Lignes comptées',conf:'Lignes conformes',ecarts:'Écarts détectés',
bilT:'Bilan du mois',bilS:'D\'où viennent vos sorties de stock, et ce qu\'elles coûtent.',
origine:'Origine des sorties non-vendues',srcAuto:'Importé depuis un système externe',srcAutoD:'Offerts, annulations, repas perso — sans ressaisie dans INVO',
srcMain:'Déclaré par l\'équipe',srcMainD:'Casse, ratés, dégustations, bouteilles entamées',
kNonVendu:'Coût des sorties non-vendues',kCA:'CA encaissé',kRatio:'Ratio matière',kEcart:'Écarts inventaire',
repart:'Répartition par motif',jrnl:'Derniers mouvements',vide:'Rien pour l\'instant',videD:'Les mouvements apparaîtront ici.',
who:'Qui utilise l\'app ?',whoS:'Choisissez votre poste dans l\'établissement.',
lang:'Langue',langS:'L\'app parle la langue de chaque membre de l\'équipe.',
saved:'Sortie enregistrée',invOk:'Inventaire validé',cleared:'Démo réinitialisée',reset:'Reset',resetS:'Restaure les produits de démonstration et retire les données locales actuelles. Une sauvegarde est téléchargée avant.',resetConfirm:'Réinitialiser la démo va remplacer les données locales actuelles. Une sauvegarde sera téléchargée avant. Continuer ?',
cTapas:'Tapas',cPlats:'Plats',cCock:'Cocktails',cVins:'Vins',cBieres:'Bières',cSofts:'Softs',cAlc:'Alcools',cDess:'Desserts',cCafe:'Café'},

en:{code:'EN',nom:'English',fl:'🇬🇧',
pvModifier:'Edit prices',pvTous:'All',pvAide:'Edit selling prices directly. The food cost ratio updates as you type. Nothing is saved until you confirm.',pvCout:'Cost',pvAvant:'was:',pvAppliquer:'Apply to all displayed products (%n)',pvAucun:'No matching product.',pvEnregistrer:'Save %n prices',pvRien:'No change',pvEnregistres:'%n prices updated',

qCoupe:'The note touches two edges of the frame: part of it may be missing.',qCoupeFort:'Incomplete document: step back or recentre to fit the whole note.',qReflet:'A reflection is brightening part of the document.',qRefletFort:'Strong reflection: part of the text is washed out. Change angle or move the light source.',qVerdictVert:'Usable photo, reading can start.',qVerdictOrange:'Imperfect but usable: preprocessing should be enough.',qVerdictRouge:'Photo likely unusable for automatic reading.',

trProduitInconnu:'“%p” is not in the catalogue: add it in Products first.',trQteInvalide:'Invalid quantity.',trMotifInconnu:'Unknown movement reason.',trAnnulSansVente:'No matching transaction to classify for this product.',trParentAbsent:'The original transaction cannot be found.',trParentInvalide:'This classification can only apply to a sale or a send-out.',trParentAutreProduit:'The original transaction is for a different product.',trDejaAnnule:'This transaction is already fully classified.',trAnnulTrop:'Classification of %q requested, but only %r remains to classify.',trStockInsuffisant:'Not enough stock: %l',trAppuyerEncore:'Tap again to record anyway.',trLiee:'linked to a transaction',trStockAlerte:'stock was insufficient at the time',annul:'Cancellation',annulD:'Cancels an existing sale',

qViseur:'Place the delivery note inside the frame',qC1:'Lay the note flat on a plain surface',qC2:'Hold the phone straight above, not at an angle',qC3:'Avoid shadows and reflections',qTitre:'Photo quality',qBonne:'Good quality, reading should go well.',qFlou:'Blurry photo: text may be unreadable. Retake it holding the phone steady.',qPeuNet:'Slightly soft photo: reading will be less reliable.',qSombre:'Photo too dark: turn on a light or move near a window.',qSurexpose:'Overexposed photo: light text may disappear.',qPeuContraste:'Little contrast between text and paper.',qTropLoin:'The note fills too little of the frame: move closer.',qUnPeuLoin:'Move a little closer for sharper text.',qIncline:'Document tilted by %a°: straighten it to align the columns.',qPetite:'Low resolution image: small text will be hard to read.',qConseilRefaire:'We recommend retaking this photo before running the reading.',

scAConfirmer:'To confirm',scConfirmerAide:'Invo suggests “%p” (%s % match). Confirm if this is the right product.',scConfirmer:'Yes, that\'s the product',scTexteLu:'Text read:',scDoublonPage:'Identical line already on another page — check it is not a duplicate.',scConfirmerDabord:'%n line(s) awaiting your confirmation before saving.',

ctrlTitre:'Consistency checks',ctrlOk:'All checks passed: quantities, prices and totals match.',ctrlMulti:'%n: quantity × price gives %c € but the note says %t €',ctrlQteVide:'%n: quantity missing or unreadable',ctrlQteEnorme:'%n: quantity of %q, unusually high',ctrlQtePetite:'%n: quantity of %q, please confirm',ctrlPxVide:'%n: unit price missing',ctrlPxEnorme:'%n: price of %p €, unusually high',ctrlPxInhab:'%n: %p € while you usually pay %h €',ctrlQteInhab:'%n: %q received while you usually receive %h',ctrlDoublonLigne:'%n appears twice identically on this note',ctrlSomme:'Lines add up to %s € but the note says %h € net (gap of %d €)',ctrlHtTva:'Net %h € + VAT %v € does not give the gross %t €',ctrlTaux:'VAT rate computed at %x %, unusual',ctrlAucuneLigne:'No usable line: enter at least one product with its quantity',ctrlBloque:'%n serious issue(s) found. Fix them, or tap again to save anyway.',ctrlValiderQuandMeme:'Save despite the issues',

scCond:'Packaging',scDe:'of',scEnUnites:'units',scConverti:'Converted to units',scMethColonnes:'table read by columns',scMethMixte:'mixed analysis',scMethLignes:'line-by-line analysis',scImageOpt:'Image optimised:',scRecadre:'cropped',scRedresse:'straightened by %a°',

scOcrBloque:'This browser blocks the reading engine. Open Invo in Safari or Chrome (rather than from a preview) to use automatic reading. Meanwhile, enter the lines manually.',scRelire:'Try reading again',

scAnalyse:'Reading document…',scPage:'Page',scPatience:'The reading engine downloads on first use. Next times will be faster.',scLu:'%n line(s) read. Please check before confirming.',scPartiel:'%n line(s) read, %i to check (highlighted in orange).',scRienLu:'No product line could be read. Enter them manually using the photo.',scOcrHorsLigne:'Automatic reading unavailable (connection needed on first use). Enter lines manually.',scOcrEchec:'Reading the document failed. Enter lines manually.',scMoteur:'Read automatically',scFiab:'confidence',scFiabBasse:'Low confidence: check every line carefully.',scVerifChamp:'To check',scLeProduit:'the product',scUnite:'Unit:',

scScannerBon:'Scan a note',scTitre:'Scan a delivery note',scCaptureS:'Photograph the note. You will check everything before saving.',scPhoto:'Take a photo',scGalerie:'Choose an image',scPages:'Pages',scAmeliorer:'Improve readability',scAmeliorerS:'Stronger contrast for faint notes',scAnalyser:'Analyse note',scAnalyse:'Analysing…',scTraitement:'Processing image…',scAucunePage:'Add at least one photo of the note.',scVerifTitre:'Check the delivery',scVerifS:'Review each line. Stock changes only after you confirm.',scOcrIndispo:'Automatic reading is not connected yet. The document is kept — enter the lines using the photo above.',scVerifiez:'Information detected. Please check before confirming.',scFournisseur:'Supplier',scNumBl:'Note no.',scDate:'Date',scProduits:'Products',scLigne:'Line',scLignes:'lines',scReconnu:'Matched',scNonReconnu:'Check',scInconnuAide:'This product was not recognised. What now?',scAssocier:'Match to a product',scCreer:'Create product',scIgnorer:'Skip',scQte:'Qty',scPu:'Unit €',scRef:'Supplier ref:',scAjouterLigne:'+ Add a line',scAucuneLigne:'No lines yet.',scLignesSaisies:'Lines',scTotal:'Total',scBrouillon:'Draft',scValider:'Confirm delivery',scBrouillonOk:'Draft saved',scBrouillons:'Drafts',scSansFournisseur:'No supplier',scValide:'Delivery confirmed, stock updated',scRienAValider:'Add at least one product with a quantity.',scFoManquant:'Enter the supplier before confirming.',scErrEnreg:'Something went wrong. Your data was not changed.',scDoublon:'This delivery looks already recorded.',scVoirExistante:'View existing delivery',scContinuer:'Continue anyway',scDocument:'Document',scDocPurge:'The document is no longer stored (storage limit reached).',scScanne:'Scanned',scManuel:'Manual',scProduitCree:'Product created',scNouveauProduit:'New product',scProduitSupprime:'Deleted product',errType:'This file is not an image.',errTaille:'Image too large (25 MB maximum).',errLecture:'Could not read the file.',errImage:'Could not read the document.',errTraitement:'Image processing failed.',

ruptLoin:'Enough stock',perteDans:'Use within %s d',perteDetail:'About %q %u will be wasted (%v €) — only %d days of shelf life.',prevPerte:'Waste risk',prevPerteS:'You have more than you will use before the use-by date.',anoPerte:'%s fresh product(s) overstocked — %v € at risk',conservation:'shelf life',fDlc:'Shelf life (days)',fDlcAide:'How many days the product keeps after delivery. Leave 0 for spirits and dry goods.',

tabPrev:'Forecast',prevVideT:'Not enough data yet',prevVideD:'Forecasts will appear once sales have been recorded.',prevBase:'Based on %s day(s) of observed activity.',prevPeuFiable:'Estimate based on a single day. Accuracy improves over time.',prevUrgent:'Order now',prevSuivre:'Watch this week',prevOk:'Comfortable stock',ruptMaintenant:'Running out now',ruptAujourdhui:'Out today',ruptDemain:'Out tomorrow',ruptDans:'Out in %s d',ruptDeja:'Out of stock',resteEn:'%s %u left',rythme:'using %s %u/day',anoRupturePrevue:'%s: forecast to run out %q',anoRupturePrevueD:'%s other product(s) affected',anoRythme:'At the current rate of %s %u per day.',

slogan:'INVO — Stay in control.',aConnexion:'Sign in',aConnexionS:'Access your venue\'s data.',aMail:'Email address',aPwd:'Password',aPwd2:'Confirm password',aSeConnecter:'Sign in',aOubli:'Forgot your password?',aOu:'or',aCreerCompte:'Create an account',aCreerS:'One account per venue. Your data stays separate from other venues.',aNom:'Your name',aEtab:'Venue name',aCreer:'Create my account',aDejaCompte:'I already have an account',aCodeTitre:'Your recovery code',aCodeS:'Write it down now. It lets you reset your password if you forget it.',aCodeNote:'This code will not be shown again. Keep it somewhere safe.',aEntrer:'Saved it, enter Invo',aOubliTitre:'Reset password',aOubliS:'Enter the recovery code you received when creating the account.',aCode:'Recovery code',aNouveauPwd:'New password',aReinit:'Reset',aRetourConnexion:'Back to sign in',aReinitOk:'Password changed. You can sign in.',aChamps:'Please fill in all fields.',aMailInvalide:'Invalid email address.',aPwdCourt:'Password must be at least 8 characters.',aPwdDiff:'The two passwords do not match.',aDejaPris:'An account already exists with this address.',aIntrouvable:'No account with this address.',aMauvaisPwd:'Incorrect password.',aCodeFaux:'Incorrect recovery code.',reglages:'Settings',reglagesS:'Venue and connected hardware.',etablissement:'Venue',nomEtab:'Name',donneesIsolees:'Separate data',donneesIsoleesS:'This venue\'s data is not visible to other accounts.',compte:'Account',seDeconnecter:'Sign out',confDeco:'Sign out of Invo?',avertLocal:'Opened as a local file: password encryption is limited. For real use, host the app over HTTPS.',materiel:'Connected hardware',materielS:'Entirely optional. Invo works normally without any hardware.',doseurs:'Electronic pourers',doseursS:'Bottles in stock',nonConfig:'Not configured',activeManuel:'Manual entry',sansDoseurs:'I don\'t use any',avecDoseurs:'I use them',futs:'Connected kegs',futsS:'Draught beer',balances:'Connected scales',balancesS:'Kitchen weighing',aVenir:'Coming soon',fermer:'Close',doseursDemo:'No pourer is connected yet. Enter a reading manually to see the variance calculation. Automatic sync will require the manufacturer\'s API.',theo:'Expected',releve:'Reading',ecart:'Variance',vsTheorique:'versus expected',theorique:'Expected:',reel:'Actual:',attention:'What needs your attention',rasT:'Nothing unusual detected',rasD:'Ratios, stock levels and variances are all within range.',anoRatio:'Food cost ratio at %s % — above target',anoRatioD:'Including %s € of unsold movements.',anoRupture:'%s product(s) out of stock',anoSeuil:'%s product(s) below par',anoDerive:'%s product(s) with repeated count variance',anoPrix:'%s purchase price(s) up',anoMarge:'%s product(s) below target margin',anoOfferts:'%s € comped over the period',anoOffertsD:'That\'s %s % of revenue.',

accesTout:'Full access',accesEquipe:'Declare, deliveries, count',
nLiv:'Deliveries',
livT:'Stock in',livS:'Log what you receive: stock goes up, prices update.',
tabRecep:'Receiving',tabCmd:'To order',
newLiv:'+ New delivery',fourn:'Supplier',dateL:'Date',
addLine:'+ Add a line',totalLiv:'Delivery total',validLiv:'Save delivery',
histLiv:'Recent deliveries',noLiv:'No delivery logged yet.',
qteRecue:'Qty received',prixU2:'Unit price',livSaved:'Delivery saved',
prixMaj:'Price updated',hausse:'Up',baisse:'Down',
cmdT:'Suggested order',cmdS:'Products that dropped below par level.',
aCommander:'To order',copierListe:'📋 Copy the list',listeCopiee:'List copied',
noCmd:'Nothing below par. All good.',
zone:'Zone',zBar:'Bar',zCave:'Cellar',zCuisine:'Kitchen',zReserve:'Store room',zToutes:'All',
tabCount:'Count',tabHist:'History',
histT:'Previous counts',noHist:'No count confirmed yet.',
derive:'Recurring drift',deriveS:'Off on several counts — worth watching.',
exportCsv:'⬇ Export (CSV)',imprimer:'🖨 Print / PDF',
addPhoto:'📷 Add a photo',photoOk:'Photo added',retirerPhoto:'Remove photo',
alertes:'Alerts',alertPrix:'Purchase price rises',alertMarge:'Items below margin',
noAlerte:'No alert. Your margins hold.',
valeurStock:'Stock value',ecartValeur:'Value of gaps',
inventaireDu:'Count of',lignesEcart:'lines off',
nCaisse:'External sales',nDec:'Declare',svc:'Service',nStock:'Products',nInv:'Count',nBil:'Report',
caisseT:'External sales feed',caisseS:'Record only stock movements from sales already completed outside INVO. INVO does not take payments.',
connected:'CONNECTED',connSub:'Last sync %s ago',
demoCaisse:'Demo: this feed simulates an external sales import. INVO does not process payments.',
vente:'Sale',offClient:'Comp — guest',offPart:'Comp — partner',offGroupe:'Comp — group',
annul:'Void',perso:'Staff meal',casse:'Breakage',rate:'Botched / redone',degus:'Tasting',entame:'Opened bottle',
offClientD:'Goodwill gesture on the floor',offPartD:'Peer, supplier, nearby venue',
offGroupeD:'Group, event, private hire',persoD:'Floor or kitchen team',
casseD:'Dropped, broken, spilled',rateD:'Burnt, missed, remade',
degusD:'Menu test, owner, supplier',entameD:'Opened, never rung up',
auto:'AUTO',manuel:'MANUAL',pause:'Pause feed',reprendre:'Resume feed',
decT:'Declare a movement',decS:'Everything that leaves stock without going through the POS.',
demoDec:'Tap a product to add it. Adjust quantities, pick the reason, submit it all at once.',
midi:'Lunch',soir:'Dinner',svcHint:'Service filters the menu: mains at lunch, tapas and cocktails at dinner.',
etape1:'1 — Products',etape2:'2 — Reason',panier:'Basket',vider:'Clear',
coutMat:'Total food cost',send:'Submit',articles:'item',articlesP:'items',choisirMotif:'Pick a reason',
stockT:'Products & ingredients',stockS:'Add, edit or remove whatever you want to track.',
tabMat:'Ingredients',tabCarte:'Menu',search:'Search…',
addMat:'Add an ingredient',editMat:'Edit ingredient',
addCarte:'Add to menu',editCarte:'Edit menu item',
fNom:'Name',fIcone:'Icon',fUnite:'Tracking unit',fAchat:'Purchase mode',
achCont:'By container',achDirect:'By unit',fContenance:'Container size',fPrixCont:'Purchase price',
fPrixU:'Unit price',fStock:'Current stock',fSeuil:'Par level',
fCat:'Category',fService:'Service',fType:'Type',fPV:'Selling price',
tFood:'Food',tDrink:'Drink',svTous:'Lunch and dinner',
fiche:'Recipe',ficheS:'What this item actually pulls from stock.',
addIng:'+ Add an ingredient',noIng:'No ingredient — food cost will be zero.',
coutRev:'Food cost',marge:'Margin',ratioP:'Ratio',
save2:'Save',del:'Delete',cancel:'Cancel',
confDel:'Delete permanently?',usedIn:'Used in %s recipe(s) — it will be removed from them.',
matSaved:'Ingredient saved',matDel:'Ingredient deleted',
carteSaved:'Item saved',carteDel:'Item deleted',
invT:'Monthly count',invS:'Count, compare, confirm. Only gaps need real work.',
attendu:'EXPECTED',compte:'COUNTED',prod:'PRODUCT',valid:'Confirm count',clear:'Clear all',
lignes:'Lines counted',conf:'Lines matching',ecarts:'Gaps found',
bilT:'Monthly report',bilS:'Where your stock movements come from, and what they cost.',
origine:'Source of unsold movements',srcAuto:'Captured by the POS',srcAutoD:'Comps, voids, staff meals — zero typing',
srcMain:'Declared by the team',srcMainD:'Breakage, waste, tastings, opened bottles',
kNonVendu:'Cost of unsold movements',kCA:'Revenue taken',kRatio:'Food cost ratio',kEcart:'Count gaps',
repart:'By reason',jrnl:'Latest movements',vide:'Nothing yet',videD:'Movements will show up here.',
who:'Who is using the app?',whoS:'Pick your role in the restaurant.',
lang:'Language',langS:'The app speaks each team member\'s language.',
saved:'Saved',invOk:'Count confirmed',cleared:'Demo reset',reset:'Reset the demo',
cTapas:'Tapas',cPlats:'Mains',cCock:'Cocktails',cVins:'Wine',cBieres:'Beer',cSofts:'Softs',cAlc:'Spirits',cDess:'Desserts',cCafe:'Coffee'},

es:{code:'ES',nom:'Español',fl:'🇪🇸',
scScannerBon:'Escanear albarán',scPhoto:'Hacer una foto',scGalerie:'Elegir imagen',scReconnu:'Reconocido',scNonReconnu:'Revisar',scValider:'Validar la entrega',scQte:'Cant.',scTotal:'Total',scFournisseur:'Proveedor',scDate:'Fecha',scProduits:'Productos',

accesTout:'Acceso completo',accesEquipe:'Declarar, entregas, inventario',
nLiv:'Entregas',
livT:'Entradas de stock',livS:'Registra lo que recibes: el stock sube, los precios se actualizan.',
tabRecep:'Recepción',tabCmd:'Por pedir',
newLiv:'+ Nueva entrega',fourn:'Proveedor',dateL:'Fecha',
addLine:'+ Añadir una línea',totalLiv:'Total de la entrega',validLiv:'Guardar la entrega',
histLiv:'Entregas recientes',noLiv:'Ninguna entrega registrada.',
qteRecue:'Cant. recibida',prixU2:'Precio unitario',livSaved:'Entrega guardada',
prixMaj:'Precio actualizado',hausse:'Subida',baisse:'Bajada',
cmdT:'Sugerencia de pedido',cmdS:'Productos por debajo del mínimo.',
aCommander:'Por pedir',copierListe:'📋 Copiar la lista',listeCopiee:'Lista copiada',
noCmd:'Nada por debajo del mínimo. Todo bien.',
zone:'Zona',zBar:'Barra',zCave:'Bodega',zCuisine:'Cocina',zReserve:'Almacén',zToutes:'Todas',
tabCount:'Contar',tabHist:'Historial',
histT:'Inventarios anteriores',noHist:'Ningún inventario validado.',
derive:'Desviación recurrente',deriveS:'Con diferencias en varios inventarios.',
exportCsv:'⬇ Exportar (CSV)',imprimer:'🖨 Imprimir / PDF',
addPhoto:'📷 Añadir una foto',photoOk:'Foto añadida',retirerPhoto:'Quitar la foto',
alertes:'Alertas',alertPrix:'Subidas de precio',alertMarge:'Platos bajo margen',
noAlerte:'Sin alertas. Tus márgenes aguantan.',
valeurStock:'Valor del stock',ecartValeur:'Valor de las diferencias',
inventaireDu:'Inventario del',lignesEcart:'líneas con diferencia',
nCaisse:'Ventas externas',nDec:'Declarar',svc:'Servicio',nStock:'Productos',nInv:'Inventario',nBil:'Informe',
caisseT:'Flujo de ventas externas',caisseS:'Registre únicamente las salidas de ventas ya realizadas fuera de INVO. INVO no cobra pagos.',
connected:'CONECTADO',connSub:'Última sincronía hace %s',
demoCaisse:'Demo: este flujo simula una importación de ventas externas. INVO no procesa pagos.',
vente:'Venta',offClient:'Invitación cliente',offPart:'Invitación socio',offGroupe:'Invitación grupo',
annul:'Anulación',perso:'Comida personal',casse:'Rotura',rate:'Fallado / rehecho',degus:'Degustación',entame:'Botella abierta',
offClientD:'Gesto comercial en sala',offPartD:'Colega, proveedor, local vecino',
offGroupeD:'Grupo, evento, privatización',persoD:'Equipo de sala o cocina',
casseD:'Caído, roto, derramado',rateD:'Quemado, fallado, rehecho',
degusD:'Prueba de carta, jefe, proveedor',entameD:'Abierta, nunca cobrada',
auto:'AUTO',manuel:'MANUAL',pause:'Pausar flujo',reprendre:'Reanudar flujo',
decT:'Declarar una salida',decS:'Todo lo que sale del stock sin pasar por la caja.',
demoDec:'Toca un producto para añadirlo. Ajusta las cantidades, elige el motivo y valida todo de una vez.',
midi:'Mediodía',soir:'Noche',svcHint:'El servicio filtra la carta: platos al mediodía, tapas y cócteles por la noche.',
etape1:'1 — Productos',etape2:'2 — Motivo',panier:'Cesta',vider:'Vaciar',
coutMat:'Coste materia total',send:'Validar',articles:'artículo',articlesP:'artículos',choisirMotif:'Elegir el motivo',
stockT:'Productos y materias',stockS:'Añade, modifica o quita lo que quieras seguir.',
tabMat:'Materias',tabCarte:'Carta',search:'Buscar…',
addMat:'Añadir una materia',editMat:'Modificar la materia',
addCarte:'Añadir a la carta',editCarte:'Modificar el producto',
fNom:'Nombre',fIcone:'Icono',fUnite:'Unidad de control',fAchat:'Modo de compra',
achCont:'Por envase',achDirect:'Por unidad',fContenance:'Capacidad',fPrixCont:'Precio de compra',
fPrixU:'Precio unitario',fStock:'Stock actual',fSeuil:'Nivel mínimo',
fCat:'Categoría',fService:'Servicio',fType:'Tipo',fPV:'Precio de venta',
tFood:'Comida',tDrink:'Bebida',svTous:'Mediodía y noche',
fiche:'Escandallo',ficheS:'Lo que el producto consume realmente del stock.',
addIng:'+ Añadir un ingrediente',noIng:'Sin ingredientes — el coste será cero.',
coutRev:'Coste materia',marge:'Margen',ratioP:'Ratio',
save2:'Guardar',del:'Eliminar',cancel:'Cancelar',
confDel:'¿Eliminar definitivamente?',usedIn:'Usado en %s receta(s) — será retirado de ellas.',
matSaved:'Materia guardada',matDel:'Materia eliminada',
carteSaved:'Producto guardado',carteDel:'Producto eliminado',
invT:'Inventario del mes',invS:'Cuenta, compara, valida. Solo las diferencias dan trabajo.',
attendu:'PREVISTO',compte:'CONTADO',prod:'PRODUCTO',valid:'Validar inventario',clear:'Borrar todo',
lignes:'Líneas contadas',conf:'Líneas correctas',ecarts:'Diferencias',
bilT:'Informe del mes',bilS:'De dónde vienen las salidas y lo que cuestan.',
origine:'Origen de las salidas no vendidas',srcAuto:'Captado por la caja',srcAutoD:'Invitaciones, anulaciones, personal — sin teclear',
srcMain:'Declarado por el equipo',srcMainD:'Roturas, fallos, degustaciones, botellas abiertas',
kNonVendu:'Coste de salidas no vendidas',kCA:'Ingresos',kRatio:'Ratio materia',kEcart:'Diferencias inventario',
repart:'Por motivo',jrnl:'Últimos movimientos',vide:'Nada por ahora',videD:'Los movimientos aparecerán aquí.',
who:'¿Quién usa la app?',whoS:'Elige tu puesto en el establecimiento.',
lang:'Idioma',langS:'La app habla el idioma de cada miembro del equipo.',
saved:'Guardado',invOk:'Inventario validado',cleared:'Demo reiniciada',reset:'Reiniciar la demo',
cTapas:'Tapas',cPlats:'Platos',cCock:'Cócteles',cVins:'Vinos',cBieres:'Cervezas',cSofts:'Refrescos',cAlc:'Licores',cDess:'Postres',cCafe:'Café'},

pt:{code:'PT',nom:'Português',fl:'🇵🇹',
scScannerBon:'Digitalizar guia',scPhoto:'Tirar uma foto',scGalerie:'Escolher imagem',scReconnu:'Reconhecido',scNonReconnu:'Verificar',scValider:'Validar a entrega',scQte:'Qtd.',scTotal:'Total',scFournisseur:'Fornecedor',scDate:'Data',scProduits:'Produtos',

accesTout:'Acesso total',accesEquipe:'Declarar, entregas, inventário',
nLiv:'Entregas',
livT:'Entradas de stock',livS:'Registe o que recebe: o stock sobe, os preços atualizam-se.',
tabRecep:'Receção',tabCmd:'A encomendar',
newLiv:'+ Nova entrega',fourn:'Fornecedor',dateL:'Data',
addLine:'+ Adicionar uma linha',totalLiv:'Total da entrega',validLiv:'Guardar a entrega',
histLiv:'Entregas recentes',noLiv:'Nenhuma entrega registada.',
qteRecue:'Qtd. recebida',prixU2:'Preço unitário',livSaved:'Entrega guardada',
prixMaj:'Preço atualizado',hausse:'Subida',baisse:'Descida',
cmdT:'Sugestão de encomenda',cmdS:'Produtos abaixo do nível mínimo.',
aCommander:'A encomendar',copierListe:'📋 Copiar a lista',listeCopiee:'Lista copiada',
noCmd:'Nada abaixo do mínimo. Está tudo bem.',
zone:'Zona',zBar:'Bar',zCave:'Adega',zCuisine:'Cozinha',zReserve:'Armazém',zToutes:'Todas',
tabCount:'Contar',tabHist:'Histórico',
histT:'Inventários anteriores',noHist:'Nenhum inventário validado.',
derive:'Desvio recorrente',deriveS:'Com diferenças em vários inventários.',
exportCsv:'⬇ Exportar (CSV)',imprimer:'🖨 Imprimir / PDF',
addPhoto:'📷 Adicionar uma foto',photoOk:'Foto adicionada',retirerPhoto:'Retirar a foto',
alertes:'Alertas',alertPrix:'Subidas de preço',alertMarge:'Pratos abaixo da margem',
noAlerte:'Sem alertas. As margens aguentam.',
valeurStock:'Valor do stock',ecartValeur:'Valor das diferenças',
inventaireDu:'Inventário de',lignesEcart:'linhas com diferença',
nCaisse:'Vendas externas',nDec:'Declarar',svc:'Serviço',nStock:'Produtos',nInv:'Inventário',nBil:'Balanço',
caisseT:'Fluxo de vendas externas',caisseS:'Registe apenas saídas de vendas já concluídas fora do INVO. O INVO não recebe pagamentos.',
connected:'LIGADO',connSub:'Última sincronização há %s',
demoCaisse:'Demo: este fluxo simula uma importação de vendas externas. O INVO não processa pagamentos.',
vente:'Venda',offClient:'Oferta cliente',offPart:'Oferta parceiro',offGroupe:'Oferta grupo',
annul:'Anulação',perso:'Refeição pessoal',casse:'Quebra',rate:'Falhado / refeito',degus:'Prova',entame:'Garrafa aberta',
offClientD:'Gesto comercial na sala',offPartD:'Colega, fornecedor, casa vizinha',
offGroupeD:'Grupo, evento, privatização',persoD:'Equipa de sala ou cozinha',
casseD:'Caiu, partiu, entornou',rateD:'Queimado, falhado, refeito',
degusD:'Teste de carta, patrão, fornecedor',entameD:'Aberta, nunca cobrada',
auto:'AUTO',manuel:'MANUAL',pause:'Pausar fluxo',reprendre:'Retomar fluxo',
decT:'Declarar uma saída',decS:'Tudo o que sai do stock sem passar pela caixa.',
demoDec:'Toque num produto para adicionar. Ajuste as quantidades, escolha o motivo e valide de uma vez.',
midi:'Almoço',soir:'Jantar',svcHint:'O serviço filtra a carta: pratos ao almoço, tapas e cocktails ao jantar.',
etape1:'1 — Produtos',etape2:'2 — Motivo',panier:'Cesto',vider:'Esvaziar',
coutMat:'Custo matéria total',send:'Validar',articles:'artigo',articlesP:'artigos',choisirMotif:'Escolher o motivo',
stockT:'Produtos e matérias',stockS:'Adicione, altere ou retire o que quiser acompanhar.',
tabMat:'Matérias',tabCarte:'Carta',search:'Procurar…',
addMat:'Adicionar matéria',editMat:'Alterar matéria',
addCarte:'Adicionar à carta',editCarte:'Alterar produto',
fNom:'Nome',fIcone:'Ícone',fUnite:'Unidade de controlo',fAchat:'Modo de compra',
achCont:'Por embalagem',achDirect:'À unidade',fContenance:'Capacidade',fPrixCont:'Preço de compra',
fPrixU:'Preço unitário',fStock:'Stock atual',fSeuil:'Nível mínimo',
fCat:'Categoria',fService:'Serviço',fType:'Tipo',fPV:'Preço de venda',
tFood:'Comida',tDrink:'Bebida',svTous:'Almoço e jantar',
fiche:'Ficha técnica',ficheS:'O que o produto consome realmente do stock.',
addIng:'+ Adicionar ingrediente',noIng:'Sem ingredientes — o custo será zero.',
coutRev:'Custo matéria',marge:'Margem',ratioP:'Rácio',
save2:'Guardar',del:'Eliminar',cancel:'Cancelar',
confDel:'Eliminar definitivamente?',usedIn:'Usado em %s receita(s) — será retirado delas.',
matSaved:'Matéria guardada',matDel:'Matéria eliminada',
carteSaved:'Produto guardado',carteDel:'Produto eliminado',
invT:'Inventário do mês',invS:'Conte, compare, valide. Só as diferenças dão trabalho.',
attendu:'PREVISTO',compte:'CONTADO',prod:'PRODUTO',valid:'Validar inventário',clear:'Apagar tudo',
lignes:'Linhas contadas',conf:'Linhas certas',ecarts:'Diferenças',
bilT:'Balanço do mês',bilS:'De onde vêm as saídas e quanto custam.',
origine:'Origem das saídas não vendidas',srcAuto:'Captado pela caixa',srcAutoD:'Ofertas, anulações, pessoal — sem escrever',
srcMain:'Declarado pela equipa',srcMainD:'Quebras, falhas, provas, garrafas abertas',
kNonVendu:'Custo das saídas não vendidas',kCA:'Receita',kRatio:'Rácio matéria',kEcart:'Diferenças inventário',
repart:'Por motivo',jrnl:'Últimos movimentos',vide:'Nada por agora',videD:'Os movimentos aparecem aqui.',
who:'Quem usa a app?',whoS:'Escolha o seu posto no estabelecimento.',
lang:'Idioma',langS:'A app fala a língua de cada membro da equipa.',
saved:'Guardado',invOk:'Inventário validado',cleared:'Demo reiniciada',reset:'Reiniciar a demo',
cTapas:'Tapas',cPlats:'Pratos',cCock:'Cocktails',cVins:'Vinhos',cBieres:'Cervejas',cSofts:'Refrigerantes',cAlc:'Licores',cDess:'Sobremesas',cCafe:'Café'},

si:{code:'සිං',nom:'සිංහල',fl:'🇱🇰',
scScannerBon:'බෙදාහැරීමේ පත්‍රය පරිලෝකනය',scPhoto:'ඡායාරූපයක් ගන්න',scGalerie:'රූපයක් තෝරන්න',scReconnu:'හඳුනාගත්',scNonReconnu:'පරීක්ෂා කරන්න',scValider:'බෙදාහැරීම තහවුරු කරන්න',scQte:'ප්‍රමාණය',scTotal:'මුළු',scFournisseur:'සැපයුම්කරු',scDate:'දිනය',scProduits:'නිෂ්පාදන',

accesTout:'සම්පූර්ණ ප්‍රවේශය',accesEquipe:'දැනුම් දීම, බෙදාහැරීම්, තොග ගණන',
nLiv:'බෙදාහැරීම්',
livT:'තොග ඇතුළත් කිරීම',livS:'ලැබෙන දේ සටහන් කරන්න: තොගය වැඩි වේ, මිල යාවත්කාලීන වේ.',
tabRecep:'ලැබීම',tabCmd:'ඇණවුම් කළ යුතු',
newLiv:'+ නව බෙදාහැරීම',fourn:'සැපයුම්කරු',dateL:'දිනය',
addLine:'+ පේළියක් එක් කරන්න',totalLiv:'බෙදාහැරීමේ එකතුව',validLiv:'බෙදාහැරීම සුරකින්න',
histLiv:'මෑත බෙදාහැරීම්',noLiv:'තවම බෙදාහැරීමක් නැත.',
qteRecue:'ලැබූ ප්‍රමාණය',prixU2:'ඒකක මිල',livSaved:'බෙදාහැරීම සුරකින ලදී',
prixMaj:'මිල යාවත්කාලීන විය',hausse:'ඉහළ',baisse:'පහළ',
cmdT:'ඇණවුම් යෝජනාව',cmdS:'අවම මට්ටමට වඩා පහළ නිෂ්පාදන.',
aCommander:'ඇණවුම් කළ යුතු',copierListe:'📋 ලැයිස්තුව පිටපත් කරන්න',listeCopiee:'ලැයිස්තුව පිටපත් විය',
noCmd:'අවම මට්ටමට වඩා පහළ කිසිවක් නැත.',
zone:'කලාපය',zBar:'බාර්',zCave:'වයින් කුටිය',zCuisine:'කුස්සිය',zReserve:'ගබඩාව',zToutes:'සියල්ල',
tabCount:'ගණන් කරන්න',tabHist:'ඉතිහාසය',
histT:'පෙර තොග ගණන්',noHist:'තවම තහවුරු කළ තොග ගණනක් නැත.',
derive:'නැවත නැවත වෙනස්වීම',deriveS:'තොග ගණන් කිහිපයක වෙනස් වී ඇත.',
exportCsv:'⬇ නිර්යාත (CSV)',imprimer:'🖨 මුද්‍රණය / PDF',
addPhoto:'📷 ඡායාරූපයක් එක් කරන්න',photoOk:'ඡායාරූපය එක් විය',retirerPhoto:'ඡායාරූපය ඉවත් කරන්න',
alertes:'අනතුරු ඇඟවීම්',alertPrix:'මිල ඉහළ යාම',alertMarge:'ලාභය අඩු ආහාර',
noAlerte:'අනතුරු ඇඟවීමක් නැත.',
valeurStock:'තොගයේ වටිනාකම',ecartValeur:'වෙනස්කම්වල වටිනාකම',
inventaireDu:'තොග ගණන',lignesEcart:'වෙනස් පේළි',
nCaisse:'බාහිර විකුණුම්',nDec:'දැනුම් දෙන්න',svc:'සේවාව',nStock:'නිෂ්පාදන',nInv:'තොග ගණන',nBil:'වාර්තාව',
caisseT:'බාහිර විකුණුම් ප්‍රවාහය',caisseS:'INVO වලින් පිටත සිදු කළ විකුණුම් වලින් ලැබෙන තොග චලනයන් පමණක් සටහන් කරන්න. INVO ගෙවීම් භාර නොගනී.',
connected:'සම්බන්ධයි',connSub:'අවසන් සමමුහුර්තය %s කට පෙර',
demoCaisse:'නිරූපණය: මෙම ප්‍රවාහය බාහිර විකුණුම් ආයාතයක් අනුකරණය කරයි. INVO ගෙවීම් සකසන්නේ නැත.',
vente:'විකුණුම',offClient:'නොමිලේ — අමුත්තා',offPart:'නොමිලේ — හවුල්කරු',offGroupe:'නොමිලේ — කණ්ඩායම',
annul:'අවලංගු',perso:'සේවක ආහාර',casse:'කැඩීම',rate:'නරක් වූ / නැවත',degus:'රස බැලීම',entame:'විවෘත බෝතලය',
offClientD:'ශාලාවේ දෙන ත්‍යාගය',offPartD:'සගයා, සැපයුම්කරු, අසල්වැසි ආපනශාලාව',
offGroupeD:'කණ්ඩායම, උත්සවය, පෞද්ගලික',persoD:'ශාලා හෝ කුස්සි කණ්ඩායම',
casseD:'වැටුණු, කැඩුණු, හැලුණු',rateD:'පිළිස්සුණු, වැරදුණු, නැවත සාදන ලද',
degusD:'මෙනු පරීක්ෂාව, හිමිකරු, සැපයුම්කරු',entameD:'විවෘත කළ, කිසිදා අය නොකළ',
auto:'ස්වයං',manuel:'අතින්',pause:'නවත්වන්න',reprendre:'නැවත අරඹන්න',
decT:'පිටවීමක් දැනුම් දෙන්න',decS:'මුදල් යන්ත්‍රය හරහා නොයන සියලු තොග පිටවීම්.',
demoDec:'නිෂ්පාදනයක් එක් කිරීමට ස්පර්ශ කරන්න. ප්‍රමාණය සකසන්න, හේතුව තෝරන්න, තහවුරු කරන්න.',
midi:'දිවා',soir:'රාත්‍රී',svcHint:'සේවාව මෙනුව පෙරහන් කරයි: දිවා ආහාරයට ප්‍රධාන ආහාර, රාත්‍රියට ටපස් සහ කොක්ටේල්.',
etape1:'1 — නිෂ්පාදන',etape2:'2 — හේතුව',panier:'කූඩය',vider:'හිස් කරන්න',
coutMat:'මුළු ද්‍රව්‍ය පිරිවැය',send:'තහවුරු කරන්න',articles:'අයිතමය',articlesP:'අයිතම',choisirMotif:'හේතුව තෝරන්න',
stockT:'නිෂ්පාදන සහ ද්‍රව්‍ය',stockS:'ඔබට අවශ්‍ය දේ එක් කරන්න, වෙනස් කරන්න හෝ ඉවත් කරන්න.',
tabMat:'ද්‍රව්‍ය',tabCarte:'මෙනුව',search:'සොයන්න…',
addMat:'ද්‍රව්‍යයක් එක් කරන්න',editMat:'ද්‍රව්‍යය වෙනස් කරන්න',
addCarte:'මෙනුවට එක් කරන්න',editCarte:'නිෂ්පාදනය වෙනස් කරන්න',
fNom:'නම',fIcone:'නිරූපකය',fUnite:'මිනුම් ඒකකය',fAchat:'මිලදී ගැනීමේ ක්‍රමය',
achCont:'බහාලුමෙන්',achDirect:'ඒකකයෙන්',fContenance:'ධාරිතාව',fPrixCont:'මිලදී ගැනීමේ මිල',
fPrixU:'ඒකක මිල',fStock:'වත්මන් තොගය',fSeuil:'අවම මට්ටම',
fCat:'වර්ගය',fService:'සේවාව',fType:'වර්ගය',fPV:'විකුණුම් මිල',
tFood:'ආහාර',tDrink:'පාන',svTous:'දිවා සහ රාත්‍රී',
fiche:'වට්ටෝරුව',ficheS:'නිෂ්පාදනය තොගයෙන් සැබවින්ම ගන්නා දේ.',
addIng:'+ අමුද්‍රව්‍යයක් එක් කරන්න',noIng:'අමුද්‍රව්‍ය නැත — පිරිවැය බිංදුව වේ.',
coutRev:'ද්‍රව්‍ය පිරිවැය',marge:'ලාභය',ratioP:'අනුපාතය',
save2:'සුරකින්න',del:'මකන්න',cancel:'අවලංගු',
confDel:'ස්ථිරවම මකන්නද?',usedIn:'වට්ටෝරු %s ක භාවිත වේ — ඒවායින් ඉවත් වේ.',
matSaved:'ද්‍රව්‍යය සුරකින ලදී',matDel:'ද්‍රව්‍යය මකන ලදී',
carteSaved:'නිෂ්පාදනය සුරකින ලදී',carteDel:'නිෂ්පාදනය මකන ලදී',
invT:'මාසික තොග ගණන',invS:'ගණන් කරන්න, සසඳන්න, තහවුරු කරන්න.',
attendu:'අපේක්ෂිත',compte:'ගණන් කළ',prod:'නිෂ්පාදනය',valid:'තහවුරු කරන්න',clear:'සියල්ල මකන්න',
lignes:'ගණන් කළ පේළි',conf:'ගැළපෙන පේළි',ecarts:'වෙනස්කම්',
bilT:'මාසික වාර්තාව',bilS:'ඔබේ තොග පිටවීම් කොහෙන්ද, කීයක් වැයද.',
origine:'නොවිකුණූ පිටවීම්වල මූලාශ්‍රය',srcAuto:'මුදල් යන්ත්‍රයෙන්',srcAutoD:'නොමිලේ දීම්, අවලංගු, සේවක ආහාර',
srcMain:'කණ්ඩායම විසින්',srcMainD:'කැඩීම්, නරක් වූ, රස බැලීම්, විවෘත බෝතල්',
kNonVendu:'නොවිකුණූ පිටවීම්වල පිරිවැය',kCA:'ලැබූ ආදායම',kRatio:'ද්‍රව්‍ය අනුපාතය',kEcart:'තොග වෙනස්කම්',
repart:'හේතුව අනුව',jrnl:'නවතම චලනයන්',vide:'තවම කිසිවක් නැත',videD:'චලනයන් මෙහි පෙන්වනු ඇත.',
who:'ඇප් එක භාවිත කරන්නේ කවුද?',whoS:'ආපනශාලාවේ ඔබේ තනතුර තෝරන්න.',
lang:'භාෂාව',langS:'ඇප් එක සෑම කණ්ඩායම් සාමාජිකයෙකුගේම භාෂාව කථා කරයි.',
saved:'සුරකින ලදී',invOk:'තොග ගණන තහවුරු විය',cleared:'නිරූපණය යළි සකසන ලදී',reset:'නිරූපණය යළි සකසන්න',
cTapas:'ටපස්',cPlats:'ප්‍රධාන ආහාර',cCock:'කොක්ටේල්',cVins:'වයින්',cBieres:'බියර්',cSofts:'මෘදු පාන',cAlc:'මධ්‍යසාර',cDess:'අතුරුපස',cCafe:'කෝපි'},

ta:{code:'தமி',nom:'தமிழ்',fl:'🇱🇰',
scScannerBon:'விநியோகச் சீட்டை ஸ்கேன் செய்',scPhoto:'புகைப்படம் எடு',scGalerie:'படத்தைத் தேர்ந்தெடு',scReconnu:'அடையாளம் காணப்பட்டது',scNonReconnu:'சரிபார்',scValider:'விநியோகத்தை உறுதிப்படுத்து',scQte:'அளவு',scTotal:'மொத்தம்',scFournisseur:'சப்ளையர்',scDate:'தேதி',scProduits:'பொருட்கள்',

accesTout:'முழு அணுகல்',accesEquipe:'பதிவு, விநியோகம், எண்ணல்',
nLiv:'விநியோகங்கள்',
livT:'கையிருப்பு உள்வரவு',livS:'பெறுவதைப் பதிவு செய்யுங்கள்: கையிருப்பு உயரும், விலைகள் புதுப்பிக்கப்படும்.',
tabRecep:'பெறுதல்',tabCmd:'ஆர்டர் செய்ய',
newLiv:'+ புதிய விநியோகம்',fourn:'சப்ளையர்',dateL:'தேதி',
addLine:'+ ஒரு வரி சேர்',totalLiv:'விநியோக மொத்தம்',validLiv:'விநியோகத்தைச் சேமி',
histLiv:'சமீபத்திய விநியோகங்கள்',noLiv:'இதுவரை விநியோகம் பதிவாகவில்லை.',
qteRecue:'பெற்ற அளவு',prixU2:'அலகு விலை',livSaved:'விநியோகம் சேமிக்கப்பட்டது',
prixMaj:'விலை புதுப்பிக்கப்பட்டது',hausse:'உயர்வு',baisse:'இறக்கம்',
cmdT:'ஆர்டர் பரிந்துரை',cmdS:'குறைந்தபட்ச அளவுக்குக் கீழே உள்ள பொருட்கள்.',
aCommander:'ஆர்டர் செய்ய',copierListe:'📋 பட்டியலை நகலெடு',listeCopiee:'பட்டியல் நகலெடுக்கப்பட்டது',
noCmd:'குறைந்தபட்சத்திற்குக் கீழே எதுவும் இல்லை.',
zone:'பகுதி',zBar:'பார்',zCave:'ஒயின் அறை',zCuisine:'சமையலறை',zReserve:'கிடங்கு',zToutes:'அனைத்தும்',
tabCount:'எண்ணு',tabHist:'வரலாறு',
histT:'முந்தைய எண்ணல்கள்',noHist:'இதுவரை உறுதிப்படுத்தப்பட்ட எண்ணல் இல்லை.',
derive:'தொடர் வேறுபாடு',deriveS:'பல எண்ணல்களில் வேறுபாடு — கவனிக்க வேண்டும்.',
exportCsv:'⬇ ஏற்றுமதி (CSV)',imprimer:'🖨 அச்சிடு / PDF',
addPhoto:'📷 ஒரு புகைப்படம் சேர்',photoOk:'புகைப்படம் சேர்க்கப்பட்டது',retirerPhoto:'புகைப்படத்தை நீக்கு',
alertes:'எச்சரிக்கைகள்',alertPrix:'கொள்முதல் விலை உயர்வு',alertMarge:'லாபம் குறைந்த உணவுகள்',
noAlerte:'எச்சரிக்கை இல்லை.',
valeurStock:'கையிருப்பு மதிப்பு',ecartValeur:'வேறுபாடுகளின் மதிப்பு',
inventaireDu:'எண்ணல்',lignesEcart:'வேறுபட்ட வரிகள்',
nCaisse:'வெளிப்புற விற்பனைகள்',nDec:'பதிவு செய்',svc:'சேவை',nStock:'பொருட்கள்',nInv:'சரக்கு எண்ணல்',nBil:'அறிக்கை',
caisseT:'வெளிப்புற விற்பனை ஓட்டம்',caisseS:'INVO க்கு வெளியே முடிந்த விற்பனைகளின் இருப்பு நகர்வுகளை மட்டும் பதிவு செய்யவும். INVO பணம் வசூலிப்பதில்லை.',
connected:'இணைக்கப்பட்டது',connSub:'கடைசி ஒத்திசைவு %s முன்பு',
demoCaisse:'மாதிரி: இந்த ஓட்டம் வெளிப்புற விற்பனை இறக்குமதியைப் பிரதிபலிக்கிறது. INVO பணப் பரிவர்த்தனைகளைச் செய்யாது.',
vente:'விற்பனை',offClient:'இலவசம் — வாடிக்கையாளர்',offPart:'இலவசம் — கூட்டாளி',offGroupe:'இலவசம் — குழு',
annul:'ரத்து',perso:'பணியாளர் உணவு',casse:'உடைவு',rate:'கெட்டது / மீண்டும்',degus:'சுவை பார்த்தல்',entame:'திறந்த பாட்டில்',
offClientD:'மண்டபத்தில் வழங்கிய சலுகை',offPartD:'சகா, சப்ளையர், அருகிலுள்ள உணவகம்',
offGroupeD:'குழு, நிகழ்வு, தனியார் விழா',persoD:'மண்டபம் அல்லது சமையலறை குழு',
casseD:'விழுந்தது, உடைந்தது, சிந்தியது',rateD:'எரிந்தது, தவறியது, மீண்டும் செய்யப்பட்டது',
degusD:'மெனு சோதனை, முதலாளி, சப்ளையர்',entameD:'திறக்கப்பட்டது, கணக்கிடப்படவில்லை',
auto:'தானியங்கி',manuel:'கையால்',pause:'இடைநிறுத்து',reprendre:'மீண்டும் தொடங்கு',
decT:'ஒரு வெளியேற்றத்தைப் பதிவு செய்',decS:'பணப்பெட்டி வழியாகச் செல்லாமல் கையிருப்பை விட்டு வெளியேறும் அனைத்தும்.',
demoDec:'ஒரு பொருளைச் சேர்க்கத் தொடவும். அளவுகளைச் சரிசெய்து, காரணத்தைத் தேர்ந்தெடுத்து, உறுதிப்படுத்தவும்.',
midi:'மதியம்',soir:'இரவு',svcHint:'சேவை மெனுவை வடிகட்டுகிறது: மதியம் முக்கிய உணவு, இரவில் தபாஸ் மற்றும் காக்டெயில்.',
etape1:'1 — பொருட்கள்',etape2:'2 — காரணம்',panier:'கூடை',vider:'காலி செய்',
coutMat:'மொத்த மூலப்பொருள் செலவு',send:'உறுதிப்படுத்து',articles:'பொருள்',articlesP:'பொருட்கள்',choisirMotif:'காரணத்தைத் தேர்ந்தெடு',
stockT:'பொருட்கள் மற்றும் மூலப்பொருட்கள்',stockS:'நீங்கள் கண்காணிக்க விரும்புவதைச் சேர்க்க, திருத்த அல்லது நீக்கவும்.',
tabMat:'மூலப்பொருட்கள்',tabCarte:'மெனு',search:'தேடு…',
addMat:'ஒரு மூலப்பொருளைச் சேர்',editMat:'மூலப்பொருளைத் திருத்து',
addCarte:'மெனுவில் சேர்',editCarte:'பொருளைத் திருத்து',
fNom:'பெயர்',fIcone:'சின்னம்',fUnite:'அளவீட்டு அலகு',fAchat:'கொள்முதல் முறை',
achCont:'கொள்கலன் வாரியாக',achDirect:'அலகு வாரியாக',fContenance:'கொள்ளளவு',fPrixCont:'கொள்முதல் விலை',
fPrixU:'அலகு விலை',fStock:'தற்போதைய கையிருப்பு',fSeuil:'குறைந்தபட்ச அளவு',
fCat:'வகை',fService:'சேவை',fType:'வகை',fPV:'விற்பனை விலை',
tFood:'உணவு',tDrink:'பானம்',svTous:'மதியம் மற்றும் இரவு',
fiche:'செய்முறை',ficheS:'இந்தப் பொருள் கையிருப்பிலிருந்து உண்மையில் எடுப்பது.',
addIng:'+ ஒரு மூலப்பொருளைச் சேர்',noIng:'மூலப்பொருள் இல்லை — செலவு பூஜ்ஜியமாக இருக்கும்.',
coutRev:'மூலப்பொருள் செலவு',marge:'லாபம்',ratioP:'விகிதம்',
save2:'சேமி',del:'நீக்கு',cancel:'ரத்து',
confDel:'நிரந்தரமாக நீக்கவா?',usedIn:'%s செய்முறையில் பயன்படுகிறது — அவற்றிலிருந்து நீக்கப்படும்.',
matSaved:'மூலப்பொருள் சேமிக்கப்பட்டது',matDel:'மூலப்பொருள் நீக்கப்பட்டது',
carteSaved:'பொருள் சேமிக்கப்பட்டது',carteDel:'பொருள் நீக்கப்பட்டது',
invT:'மாதாந்திர எண்ணல்',invS:'எண்ணுங்கள், ஒப்பிடுங்கள், உறுதிப்படுத்துங்கள்.',
attendu:'எதிர்பார்த்த',compte:'எண்ணிய',prod:'பொருள்',valid:'உறுதிப்படுத்து',clear:'அனைத்தையும் அழி',
lignes:'எண்ணிய வரிகள்',conf:'பொருந்திய வரிகள்',ecarts:'வேறுபாடுகள்',
bilT:'மாதாந்திர அறிக்கை',bilS:'உங்கள் கையிருப்பு வெளியேற்றங்கள் எங்கிருந்து வருகின்றன, எவ்வளவு செலவாகும்.',
origine:'விற்கப்படாத வெளியேற்றங்களின் ஆதாரம்',srcAuto:'பணப்பெட்டியால் பதிவு',srcAutoD:'இலவசம், ரத்து, பணியாளர் உணவு',
srcMain:'குழுவால் பதிவு',srcMainD:'உடைவு, கெட்டவை, சுவை, திறந்த பாட்டில்கள்',
kNonVendu:'விற்கப்படாத வெளியேற்றச் செலவு',kCA:'பெறப்பட்ட வருவாய்',kRatio:'மூலப்பொருள் விகிதம்',kEcart:'எண்ணல் வேறுபாடுகள்',
repart:'காரணத்தின்படி',jrnl:'சமீபத்திய நகர்வுகள்',vide:'இதுவரை எதுவும் இல்லை',videD:'நகர்வுகள் இங்கே தோன்றும்.',
who:'செயலியை யார் பயன்படுத்துகிறார்?',whoS:'உணவகத்தில் உங்கள் பதவியைத் தேர்ந்தெடுக்கவும்.',
lang:'மொழி',langS:'ஒவ்வொரு குழு உறுப்பினரின் மொழியிலும் செயலி பேசுகிறது.',
saved:'சேமிக்கப்பட்டது',invOk:'எண்ணல் உறுதிப்படுத்தப்பட்டது',cleared:'மாதிரி மீட்டமைக்கப்பட்டது',reset:'மாதிரியை மீட்டமை',
cTapas:'தபாஸ்',cPlats:'முக்கிய உணவு',cCock:'காக்டெயில்',cVins:'ஒயின்',cBieres:'பீர்',cSofts:'குளிர்பானம்',cAlc:'மது',cDess:'இனிப்பு',cCafe:'காபி'}};

